BinaryStudioAcademy/bsa-2021-watchdog

frontend/src/app/app.module.ts
frontend/src/app/core/helpers/error.interceptor.ts
frontend/src/app/core/services/http-internal.service.ts

Add base architecture for HttpErrorInterceptor and HttpInternalService

Implement generic HTTP client

---

frontend/src/app/app.module.ts
frontend/src/app/core/helpers/error.interceptor.ts
frontend/src/app/core/services/http-internal.service.ts

Add base architecture for HttpErrorInterceptor and HttpInternalService

Implement generic HTTP client with error handling

---

frontend/src/app/modules/home/home-page/home-page.component.sass
frontend/src/app/modules/home/projects/create-project/create-project.component.sass
frontend/src/app/modules/home/projects/projects/projects.component.sass
frontend/src/app/modules/landing/components/landing-content/landing-content.component.sass
frontend/src/app/modules/landing/components/landing-header/landing-header.component.sass
frontend/src/app/modules/landing/components/landing-platforms/landing-platforms.component.sass
frontend/src/styles/mixins.sass

Added disable-selection mixin and applied to styles

---

frontend/src/app/modules/home/home-page/home-page.component.sass

Header fix bugs

---

frontend/src/app/modules/landing/components/landing-content-item/landing-content-item.component.html
frontend/src/app/modules/landing/components/landing-content-item/landing-content-item.component.sass
frontend/src/app/modules/landing/components/landing-content/landing-content.component.ts
frontend/src/app/modules/landing/components/landing-demo/landing-demo.component.sass
frontend/src/app/modules/landing/components/landing-footer/landing-footer.component.html
frontend/src/app/modules/landing/components/landing-footer/landing-footer.component.sass
frontend/src/app/modules/landing/components/landing-header/landing-header.component.html
frontend/src/app/modules/landing/components/landing-header/landing-header.component.sass

Fix hovers and content of landing page

---

frontend/src/app/core/services/team.service.ts
frontend/src/app/modules/home/projects/create-project/create-project.component.ts
frontend/src/app/modules/team/teams/other-teams/other-teams.component.ts
frontend/src/app/modules/team/teams/teams.component.ts
frontend/src/app/modules/team/teams/user-teams/user-teams.component.ts

Please merge this changes into main, because this bug are in there also. 
Fixed. Now no errors.

HotFix! Removed HttpResponse from team service

---

frontend/src/app/modules/home/dashboard/tile-menu/tile-menu.component.html
frontend/src/app/modules/home/dashboard/tile-menu/tile-menu.component.sass

Yehor told me that my styles is breaking all components that used menu.
So, already i have found a solution. I just used styleClass with ng-deep, and now no conflicts

Fixed styles

---

frontend/src/app/core/components/toast-notification/toast-notification.component.html
frontend/src/app/core/components/toast-notification/toast-notification.component.sass
frontend/src/app/core/interceptors/error.interceptor.ts
frontend/src/app/core/services/toast-notification.service.ts

Now text is wrapped on overflow.
I can also increase width of toast notifications if you want. 
But if i increase width of text, it will break a close button, i can remove it if you want.

Fix: Toast Notifications

---

frontend/src/app/modules/authorization/login-form/login-form.component.sass
frontend/src/app/modules/home/projects/create-project/create-project.component.sass
frontend/src/app/modules/registration/registration-form/registration-form.component.sass
frontend/src/styles/variables.sass

Fix input height

---

frontend/src/app/modules/home/organization/organization-settings/organization-settings.component.html
frontend/src/app/modules/home/projects/create-project/create-project.component.html
frontend/src/app/modules/team/team-info/team-info.component.html
frontend/src/styles/index.sass

Update buttons styles

---

frontend/src/app/modules/home/dashboard/tiles/top-active-issues-tile/top-active-issues-tile.component.sass

Fix input tile height

---

frontend/src/app/modules/authorization/login-form/login-form.component.html
frontend/src/app/modules/registration/registration-form/registration-form.component.html

Fix buttons styles

---

frontend/src/app/modules/home/dashboard/dashboard.component.sass

Because someone after update tile header, forgot to increase tile height.
Height must be a fixed value

Top Active Issue Tile height

---

frontend/src/app/modules/home/dashboard/dashboard.component.sass
frontend/src/app/modules/home/modals/dashboard/add-dashboard.component.ts
frontend/src/app/modules/home/modals/dashboard/dashboard-template.html
frontend/src/app/modules/home/modals/dashboard/dashboard-template.sass
frontend/src/app/modules/home/modals/dashboard/update-dashboard.component.ts

Change dashdoard dropdown to grid

---

frontend/src/app/modules/home/home-page/home-page.component.html
frontend/src/app/modules/home/home-page/home-page.component.sass
frontend/src/app/modules/home/home-page/home-page.component.ts
frontend/src/app/modules/home/modals/dashboard/dashboard-template.html
frontend/src/app/modules/home/modals/dashboard/dashboard-template.sass
frontend/src/app/modules/home/organization/organization-menu/organization-menu.component.html
frontend/src/app/modules/home/organization/organization-menu/organization-menu.component.ts
frontend/src/app/modules/home/organization/organization-menu/organization-menu.style.sass

Collapse sidebar

---

frontend/src/app/modules/home/issues/issues.component.html
frontend/src/app/modules/home/issues/issues.component.sass

Description : The horizontal scroll is displayed on the Issues page

Add overflow-x for scrolling

---

frontend/src/app/core/services/authentication.service.ts
frontend/src/app/core/services/member.service.ts
frontend/src/app/core/services/organization.service.ts
frontend/src/app/modules/home/home-page/home-page.component.html
frontend/src/app/modules/home/home-page/home-page.component.sass
frontend/src/app/modules/home/issues/issues.component.sass
frontend/src/app/modules/home/organization/organization-menu/organization-menu.component.html
frontend/src/app/modules/home/organization/organization-menu/organization-menu.component.ts
frontend/src/app/modules/home/organization/organization-menu/organization-menu.style.sass
frontend/src/styles/mixins.sass
frontend/src/styles/variables.sass

Redisign organization-menu

---

frontend/src/app/modules/home/projects/create-project/create-project.component.html
frontend/src/app/modules/home/projects/create-project/create-project.component.sass

Update header and button

---

frontend/src/app/modules/home/dashboard/tiles/top-active-issues-tile/top-active-issues-tile.component.html
frontend/src/app/modules/home/dashboard/tiles/top-active-issues-tile/top-active-issues-tile.component.sass

Add text overflow and tooltip full name

---

frontend/src/app/modules/home/issues/issue-details/breadcrumbs/breadcrumbs.component.ts
frontend/src/app/modules/home/issues/issue-details/issue-events/issue-events.component.html
frontend/src/app/modules/home/issues/issue-details/issue-events/issue-events.component.sass

Fix breadcrums changing and current label to current event

---

frontend/src/app/modules/members/members-page/members-page.component.html
frontend/src/app/modules/members/members-page/members-page.component.ts

Fix member role

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/core/services/table-export.service.ts
frontend/src/app/modules/home/issues/issue-details/issue-details-page/issue-details-page.component.html
frontend/src/app/modules/home/issues/issue-details/issue-events/issue-events.component.html
frontend/src/app/modules/home/issues/issue-details/issue-events/issue-events.component.sass
frontend/src/app/modules/home/issues/issue-details/issue-events/issue-events.component.ts
frontend/src/app/modules/home/issues/issues.component.html
frontend/src/app/modules/home/issues/issues.component.sass
frontend/src/app/modules/home/issues/issues.component.ts
frontend/src/app/modules/members/members-page/members-page.component.html
frontend/src/app/modules/members/members-page/members-page.component.sass
frontend/src/app/modules/members/members-page/members-page.component.ts
frontend/src/app/shared/models/export/IssueInfoExport.ts
frontend/src/app/shared/models/export/IssueMessageExport.ts
frontend/src/app/shared/models/export/MemberExport.ts

Export table feature

---

backend/Watchdog.Core/Watchdog.Core.API/Controllers/IssuesController.cs
backend/Watchdog.Core/Watchdog.Core.BLL/Services/Abstract/IIssueService.cs
backend/Watchdog.Core/Watchdog.Core.BLL/Services/IssueService.cs
frontend/src/app/core/services/http-internal.service.ts
frontend/src/app/core/services/issue.service.ts
frontend/src/app/modules/home/issues/issues.component.html
frontend/src/app/modules/home/issues/issues.component.sass
frontend/src/app/modules/home/issues/issues.component.ts

Issues page status tabs

---

frontend/src/app/modules/home/issues/issues.component.html
frontend/src/app/modules/home/issues/issues.component.sass

Fixes: html page a little bit reworked, sass full refactoring

Issues page template rework

---

frontend/src/app/core/services/table-export.service.ts

Added current time into the file name + refactoring

---

backend/Watchdog.Core/Watchdog.Core.API/Controllers/IssuesController.cs
backend/Watchdog.Core/Watchdog.Core.BLL/Services/Abstract/IIssueService.cs
backend/Watchdog.Core/Watchdog.Core.BLL/Services/IssueService.cs
backend/Watchdog.Core/Watchdog.Core.Common/DTO/Issue/CountOfIssuesByStatusDTO.cs
backend/Watchdog.Core/Watchdog.Core.Common/DTO/Issue/CountOfIssuesByStatusDto.cs
frontend/src/app/core/services/issue.service.ts
frontend/src/app/modules/home/dashboard/tiles/top-active-issues-tile/top-active-issues-tile.component.ts
frontend/src/app/modules/home/issues/issues.component.html
frontend/src/app/modules/home/issues/issues.component.sass
frontend/src/app/modules/home/issues/issues.component.ts
frontend/src/app/shared/models/issue/count-of-issues-by-status.ts

count badges on tabs,
top-active-issues-tile optimized request

Issue page count badges

---

frontend/src/app/modules/home/projects/edit/configure/configurations/asp-net-core/asp-net-core.constants.ts
frontend/src/app/modules/home/projects/edit/configure/configurations/dot-net/dot-net.component.html
frontend/src/app/modules/home/projects/edit/configure/configurations/dot-net/dot-net.component.ts
frontend/src/app/modules/home/projects/edit/configure/configurations/dot-net/dot-net.constants.ts
frontend/src/app/modules/home/projects/edit/configure/configure-wrapper/configure-wrapper.component.html
frontend/src/app/modules/home/projects/projects.module.ts

Added .NET support

---

frontend/src/app/modules/home/load-testing/tests/tests.component.html
frontend/src/app/modules/home/load-testing/tests/tests.component.sass

Fix bugs with test page

---

frontend/src/app/modules/home/dashboard/tile-menu/tile-menu.component.sass

Fix tile menu styles

---

frontend/src/app/modules/home/projects/edit/edit.component.html

Change tabs order

---

frontend/src/app/modules/team/teams/teams.component.sass

Elipsis when only when long name

---

frontend/src/app/modules/home/dashboard/tiles/most-common-countries-tile/most-common-countries-tile.component.html
frontend/src/app/modules/home/dashboard/tiles/top-active-issues-tile/top-active-issues-tile.component.html
frontend/src/app/modules/home/dashboard/tiles/top-responses-time-tile/top-responses-time-tile.component.html

Fix paginators

---

frontend/src/app/modules/user/components/user-profile-settings/user-profile-settings.component.html
frontend/src/app/modules/user/components/user-profile-settings/user-profile-settings.component.ts
frontend/src/app/modules/user/components/user-profile/user-profile.component.sass

Fix user page validation

---

frontend/src/app/modules/home/home-page/home-page.component.html
frontend/src/app/modules/home/organization/create-organization/create-organization.component.html
frontend/src/app/modules/home/organization/create-organization/create-organization.component.ts
frontend/src/app/modules/home/organization/organization-menu/organization-menu.component.html

When no organizations user can't close modal

Fix user no organizations

---

frontend/src/app/modules/members/invite/invite.component.html
frontend/src/app/modules/members/invite/invite.component.sass

Fix invite member width
